import { useState } from "react";
import { BarView, MultiLine } from "../components/charts";
import { Card, DataDisclosure, DataTable, ErrorState, MultiSelect, NoData, Notice, PageIntro, PageSkeleton, ScopeFooter, Select, StatCard, Tabs, NumberInput } from "../components/ui";
import { useApi } from "../hooks";
import { scaledCurrency } from "../format";

const growthDescription = "Classifies export growth patterns, compares country trajectories, measures product diversification, decomposes underlying drivers, and evaluates targets against a validated trend forecast.";

export function GrowthPage({ filters, onResetFilters, onSelectCountry }) {
  const [tab, setTab] = useState("Growth profiles");
  const [params, setParams] = useState({});
  const state = useApi("/api/growth", filters, params);
  const data = state.data;
  const patch = (key, value) => setParams((previous) => ({ ...previous, [key]: value }));
  const resetPage = () => { setParams({}); onResetFilters(); };
  if (!data && state.loading) return <><PageIntro title="Country growth" subtitle={growthDescription} /><PageSkeleton page="growth" /></>;
  if (state.error) return <><PageIntro title="Country growth" subtitle={growthDescription} /><ErrorState error={state.error} retry={state.retry} /></>;
  return <><PageIntro title="Country growth" subtitle={growthDescription} scope={data.scope} /><div className="page-stack"><Tabs items={["Growth profiles", "Country trends", "Diversification", "Underlying drivers", "Target and forecast"]} active={tab} onChange={setTab} />
    {tab === "Growth profiles" && <Profiles data={data} params={params} patch={patch} loading={state.loading} onReset={resetPage} onSelectCountry={onSelectCountry} />}
    {tab === "Country trends" && <CountryTrends data={data} patch={patch} loading={state.loading} onReset={resetPage} onSelectCountry={onSelectCountry} />}
    {tab === "Diversification" && <Diversification data={data.diversification} patch={patch} loading={state.loading} onReset={resetPage} />}
    {tab === "Underlying drivers" && <Drivers data={data} patch={patch} loading={state.loading} onReset={resetPage} />}
    {tab === "Target and forecast" && <Target data={data} params={params} patch={patch} loading={state.loading} onReset={resetPage} />}
    <ScopeFooter scope={data.scope} />
  </div></>;
}

function Profiles({ data, params, patch, loading, onReset, onSelectCountry }) {
  return <Card className="white" title="Export growth patterns" hint="Classify countries by speed and volatility over a window."><div className="controls"><Select label="From" value={params.growth_from || data.years[0]} onChange={(value) => patch("growth_from", Number(value))}>{data.years.map((year) => <option key={year}>{year}</option>)}</Select><Select label="To" value={params.growth_to || data.years.at(-1)} onChange={(value) => patch("growth_to", Number(value))}>{data.years.map((year) => <option key={year}>{year}</option>)}</Select><MultiSelect label="Filter archetype" options={data.archetypes} value={params.archetypes || []} onChange={(value) => patch("archetypes", value)} /></div>{data.profiles.length ? <><div className="grid-2 chart-grid"><div className="chart-panel"><h3 className="chart-title">Archetype distribution</h3><BarView data={data.archetype_counts} x="archetype" y="count" loading={loading} onReset={onReset} /></div><div className="chart-panel"><h3 className="chart-title">Country export CAGR</h3><BarView data={[...data.profiles].slice(0,15).reverse()} x="country" y="cagr_pct" horizontal signColors percent loading={loading} onReset={onReset} onSelectCountry={onSelectCountry} /></div></div><DataTable rows={data.profiles} columns={["country","archetype","cagr_pct","total_change_pct","yoy_std","shock_year","shock_yoy_pct","export_start_b","export_end_b"]} /></> : <NoData onReset={onReset} />}</Card>;
}

function CountryTrends({ data, patch, loading, onReset, onSelectCountry }) {
  const selected = data.compare_countries;
  const focusedRows = data.comparison.filter((row) => row.country_or_area === data.focus_country && row.yoy_pct !== null);
  return <Card className="white" title="Detailed export trends" hint="Select countries to compare trajectories and year-over-year swings."><div className="controls"><MultiSelect label="Countries" options={data.country_options} value={selected} onChange={(value) => patch("compare_countries", value)} max={6} /><Select label="Focus country" value={data.focus_country || ""} onChange={(value) => patch("focus_country", value)}>{selected.map((country) => <option key={country}>{country}</option>)}</Select></div>{selected.length ? <><h3 className="chart-title">Export value</h3><MultiLine data={data.comparison} keys={selected} yKey="trade_billions" seriesKey="country_or_area" currency scale={1e9} loading={loading} onReset={onReset} onSelectCountry={onSelectCountry} /><DataDisclosure rows={data.comparison} columns={["year","country_or_area","trade_usd","yoy_pct"]} />{focusedRows.length > 0 && <><h3 className="chart-title">Year-over-year change</h3><BarView data={focusedRows} x="year" y="yoy_pct" signColors percent loading={loading} onReset={onReset} /></>}{data.focus_profile[0] && <div className="grid-4 mt-6"><StatCard label="Growth type" value={data.focus_profile[0].archetype} loading={loading} /><StatCard label="CAGR" value={`${data.focus_profile[0].cagr_pct > 0 ? "+" : ""}${data.focus_profile[0].cagr_pct}%`} direction={data.focus_profile[0].cagr_pct >= 0 ? "up" : "down"} loading={loading} /><StatCard label="Total change" value={`${data.focus_profile[0].total_change_pct > 0 ? "+" : ""}${data.focus_profile[0].total_change_pct}%`} direction={data.focus_profile[0].total_change_pct >= 0 ? "up" : "down"} loading={loading} /><StatCard label="Largest shock" value={data.focus_profile[0].shock_year || "-"} context={data.focus_profile[0].shock_yoy_pct !== null ? `${data.focus_profile[0].shock_yoy_pct}%` : ""} loading={loading} /></div>}</> : <NoData onReset={onReset} />}</Card>;
}

function Diversification({ data, patch, loading, onReset }) {
  const current = data.current;
  const first = data.series[0];
  const delta = current && first ? current.hhi - first.hhi : 0;
  return <Card className="white" title="Product diversification" hint="HHI is the sum of each product category's squared trade share. Values closer to 1 indicate concentration; lower values indicate a broader mix."><div className="controls"><Select label="Flow" value={data.flow || ""} onChange={(value) => patch("diversification_flow", value)}>{data.flows.map((flow) => <option key={flow}>{flow}</option>)}</Select><Select label="Country" value={data.country || ""} onChange={(value) => patch("diversification_country", value)}>{data.countries.map((country) => <option key={country}>{country}</option>)}</Select><Select label="Reference year" value={data.year || ""} onChange={(value) => patch("diversification_year", Number(value))}>{data.years.map((year) => <option key={year}>{year}</option>)}</Select></div>{!current ? <NoData onReset={onReset} /> : <><div className="grid-4"><StatCard label="HHI concentration" value={current.hhi.toFixed(3)} delta={`${delta >= 0 ? "+" : ""}${delta.toFixed(3)} vs ${first.year}`} direction={delta > 0 ? "down" : delta < 0 ? "up" : "neutral"} /><StatCard label="Effective categories" value={current.effective_categories.toFixed(1)} /><StatCard label="Top category share" value={`${(current.top_category_share * 100).toFixed(1)}%`} /><StatCard label="Diversification score" value={`${(current.diversification_score * 100).toFixed(1)}/100`} /></div>{data.conditional && <Notice tone="warning">Conditional result: shares are renormalized within the selected category basket.</Notice>}<div className="grid-2 chart-grid mt-6"><div className="chart-panel"><h3 className="chart-title">HHI over time</h3><MultiLine data={data.series.map((row) => ({ ...row, series: "HHI", value: row.hhi }))} keys={["HHI"]} loading={loading} onReset={onReset} /></div><div className="chart-panel"><h3 className="chart-title">Effective categories</h3><MultiLine data={data.series.map((row) => ({ ...row, series: "Effective categories", value: row.effective_categories }))} keys={["Effective categories"]} loading={loading} onReset={onReset} /></div></div><DataDisclosure rows={data.series} /><h3 className="chart-title">Largest category shares</h3><BarView data={[...data.contributions].slice(0,12).reverse()} x="short_label" y="share_pct" horizontal percent loading={loading} onReset={onReset} /><DataTable rows={data.contributions} columns={["rank","short_label","trade_billions","share_pct","hhi_contribution_pct"]} columnLabels={{ short_label: "Category" }} /><h3 className="chart-title">Country comparison</h3><DataTable rows={data.ranking} columns={["country_or_area","hhi","effective_categories","diversification_score","top_category_share","observed_categories","coverage_pct"]} /></>}</Card>;
}

function Drivers({ data, patch, loading, onReset }) {
  const drivers = data.drivers;
  return <Card className="white" title="Probable underlying causes" hint="Break export change into commodity categories, volumes, and unit prices."><div className="controls"><Select label="Country" value={drivers.country || ""} onChange={(value) => patch("driver_country", value)}>{data.country_options.map((country) => <option key={country}>{country}</option>)}</Select><Select label="From" value={drivers.year_from} onChange={(value) => patch("driver_from", Number(value))}>{data.years.map((year) => <option key={year}>{year}</option>)}</Select><Select label="To" value={drivers.year_to} onChange={(value) => patch("driver_to", Number(value))}>{data.years.map((year) => <option key={year}>{year}</option>)}</Select></div>{drivers.summary?.narrative ? <><Notice>{drivers.summary.narrative}</Notice><div className="mt-4"><StatCard label={`Export change (${drivers.year_from} to ${drivers.year_to})`} value={scaledCurrency(drivers.summary.total_change_b, 1e9)} delta={`${drivers.summary.total_change_pct > 0 ? "+" : ""}${drivers.summary.total_change_pct}%`} direction={drivers.summary.total_change_pct >= 0 ? "up" : "down"} /></div><BarView data={drivers.rows} x="short_label" y="value_change_b" signColors currency scale={1e9} loading={loading} onReset={onReset} /><DataTable rows={drivers.rows} columns={["short_label","value_change_b","weight_change_k_t","volume_effect_b","price_effect_b","primary_driver"]} columnLabels={{ short_label: "Category", value_change_b: "Changes_Billions (USD)" }} /></> : <NoData onReset={onReset} />}</Card>;
}

function Target({ data, params, patch, loading, onReset }) {
  const target = data.target;
  const plan = target.plan;
  const forecast = target.forecast;
  const targetYear = params.target_year || plan?.target_year || ((target.baseline_year || 2016) + 5);
  const targetValue = params.target_value || plan?.target_value || ((target.baseline_value || 1) * 1.5);
  const chartRows = [
    ...target.trajectory.map((row) => ({ ...row, series: "Actual" })),
    ...(plan?.path || []).map((row) => ({ ...row, series: "Required path" })),
    ...(forecast?.series || []).map((row) => ({ ...row, series: "Trend scenario" })),
  ];
  return <Card className="white" title="Export target planner" hint="Set a future goal and compare the required path with a validated trend scenario."><div className="controls"><Select label="Country" value={target.country || ""} onChange={(value) => patch("target_country", value)}>{data.country_options.map((country) => <option key={country}>{country}</option>)}</Select><Select label="Metric" value={target.metric} onChange={(value) => patch("target_metric", value)}><option value="value">Export value ($B)</option><option value="volume">Export volume (kt)</option></Select><Select label="Baseline year" value={target.baseline_year || ""} onChange={(value) => patch("baseline_year", Number(value))}>{target.available_years.map((year) => <option key={year}>{year}</option>)}</Select><NumberInput label="Target year" value={targetYear} min={(target.baseline_year || 0) + 1} max={(target.baseline_year || 0) + 20} onChange={(value) => patch("target_year", value)} /><NumberInput label="Target value" value={targetValue} min={.01} step={.1} onChange={(value) => patch("target_value", value)} /><Select label="Forecast horizon" value={params.forecast_horizon || 5} onChange={(value) => patch("forecast_horizon", Number(value))}>{[3,4,5,6,7,8,9,10].map((year) => <option key={year}>{year}</option>)}</Select></div>{!target.baseline_year ? <NoData onReset={onReset} /> : !plan ? <Notice tone="warning">Target must exceed the baseline value.</Notice> : <><div className="grid-4"><StatCard label={`Baseline (${target.baseline_year})`} value={target.metric === "value" ? scaledCurrency(target.baseline_value, 1e9) : `${target.baseline_value.toFixed(1)} kt`} /><StatCard label={`Target (${plan.target_year})`} value={target.metric === "value" ? scaledCurrency(plan.target_value, 1e9) : `${plan.target_value.toFixed(1)} kt`} /><StatCard label="Required CAGR" value={`${plan.required_cagr_pct > 0 ? "+" : ""}${plan.required_cagr_pct}%`} /><StatCard label="Average annual increase" value={target.metric === "value" ? scaledCurrency(plan.required_annual_increase, 1e9) : plan.required_annual_increase.toFixed(2)} /></div><h3 className="chart-title">Target trajectory</h3><MultiLine data={chartRows} keys={["Actual","Required path","Trend scenario"]} currency={target.metric === "value"} scale={target.metric === "value" ? 1e9 : 1} loading={loading} onReset={onReset} /><DataDisclosure rows={chartRows} />{forecast ? <><Notice tone={forecast.beats_naive ? "success" : "warning"}>Rolling validation n={forecast.validation_observations}: MAE {forecast.mae?.toFixed(2)}, MAPE {forecast.mape?.toFixed(1)}%, naive MAE {forecast.naive_mae?.toFixed(2)}. The model {forecast.beats_naive ? "beats" : "does not beat"} the naive baseline.</Notice><DataTable rows={plan.path} /></> : <Notice>At least five positive historical observations are required for the trend scenario.</Notice>}</>}</Card>;
}
