import { useEffect, useState } from "react";
import { Download, Play } from "lucide-react";
import { api, exportUrl } from "../api";
import { AreaTimeline, BarView, Heatmap, MultiArea, MultiLine, ScatterView, TreeMapView } from "../components/charts";
import { Card, DataDisclosure, DataTable, ErrorState, MultiSelect, NoData, Notice, NumberInput, PageIntro, PageSkeleton, ScopeFooter, Section, Select, StatCard, Tabs } from "../components/ui";
import { useApi } from "../hooks";
import { categoryOptionLabel, compact } from "../format";

function LoadingPage({ state, page, title, subtitle, children }) {
  if (!state.data && state.loading) return <><PageIntro title={title} subtitle={subtitle} /><PageSkeleton page={page} /></>;
  if (state.error) return <><PageIntro title={title} subtitle={subtitle} /><ErrorState error={state.error} retry={state.retry} /></>;
  return children;
}

export function ProductsPage({ filters, onResetFilters }) {
  const [tab, setTab] = useState("Categories");
  const [params, setParams] = useState({});
  const [search, setSearch] = useState("");
  const state = useApi("/api/products", filters, params);
  const data = state.data;
  const patch = (key, value) => setParams((previous) => ({ ...previous, [key]: value }));
  const resetPage = () => { setParams({}); setSearch(""); onResetFilters(); };
  return <LoadingPage state={state} page="products" title="Products" subtitle="Ranks product categories by trade value, compares selected category trends over time, and lets you search detailed commodities within the active filters.">{data && <><PageIntro title="Products" subtitle="Ranks product categories by trade value, compares selected category trends over time, and lets you search detailed commodities within the active filters." scope={data.scope} /><div className="page-stack"><Tabs items={["Categories","Trends","Search"]} active={tab} onChange={setTab} />
    {tab === "Categories" && <Card className="white chart-card" title="Leading product categories"><div className="controls"><Select label="Top categories" value={params.top_n || 15} onChange={(value) => patch("top_n", Number(value))}>{[5,10,15,20,25,30].map((n) => <option key={n}>{n}</option>)}</Select></div><TreeMapView data={data.categories} loading={state.loading} onReset={resetPage} /><DataDisclosure rows={data.categories} columns={["short_label","trade_usd"]} /></Card>}
    {tab === "Trends" && <Card className="white chart-card" title="Category trends"><div className="controls"><MultiSelect searchable label="Plot categories" options={data.category_options} value={data.trend_categories} onChange={(value) => patch("trend_categories", value)} max={8} formatOption={(value) => categoryOptionLabel(value, data.category_labels)} /></div>{data.trends.length ? <><MultiLine data={data.trends} keys={[...new Set(data.trends.map((row) => row.label))]} yKey="trade_billions" seriesKey="label" currency scale={1e9} loading={state.loading} onReset={resetPage} /><DataDisclosure rows={data.trends} columns={["year","label","trade_usd"]} /></> : <NoData onReset={resetPage} />}</Card>}
    {tab === "Search" && <Card className="white"><div className="controls"><label className="control"><span>Commodity or HS code</span><input className="input" placeholder="oil, 2709, wheat" value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === "Enter" && patch("search", search)} /></label><button className="button" onClick={() => patch("search", search)}>Search</button></div>{params.search ? <DataTable rows={data.search} /> : <Notice>Enter a search term.</Notice>}</Card>}
    <ScopeFooter scope={data.scope} /></div></>}</LoadingPage>;
}

export function WhyPage({ filters, onResetFilters }) {
  const [tab, setTab] = useState("Root cause");
  const [params, setParams] = useState({});
  const state = useApi("/api/why", filters, params);
  const data = state.data;
  const patch = (key, value) => setParams((previous) => ({ ...previous, [key]: value }));
  const resetPage = () => { setParams({}); onResetFilters(); };
  return <LoadingPage state={state} page="why" title="Why did it change?" subtitle="Compares two periods to identify country and category gains or declines, reviews selected years side by side, and highlights countries performing below the median.">{data && <><PageIntro title="Why did it change?" subtitle="Compares two periods to identify country and category gains or declines, reviews selected years side by side, and highlights countries performing below the median." scope={data.scope} /><div className="page-stack"><Tabs items={["Root cause","Period comparison","Underperformers"]} active={tab} onChange={setTab} />
    {tab === "Root cause" && <Section title="Driver analysis"><Card className="white"><div className="controls"><Select label="From" value={data.compare_from} onChange={(value) => patch("compare_from", Number(value))}>{data.years.map((year) => <option key={year}>{year}</option>)}</Select><Select label="To" value={data.compare_to} onChange={(value) => patch("compare_to", Number(value))}>{data.years.map((year) => <option key={year}>{year}</option>)}</Select></div>{data.drivers ? <><StatCard label="Total trade change" value={`${data.drivers.total_change_pct > 0 ? "+" : ""}${data.drivers.total_change_pct?.toFixed(1)}%`} direction={data.drivers.total_change_pct >= 0 ? "up" : "down"} loading={state.loading} /><div className="grid-2 mt-6"><TableBlock kind="category" title="Largest category declines" rows={data.drivers.top_category_declines} /><TableBlock kind="category" title="Largest category gains" rows={data.drivers.top_category_gains} /><TableBlock kind="country" title="Countries that lost the most" rows={data.drivers.top_country_declines} /><TableBlock kind="country" title="Countries that gained the most" rows={data.drivers.top_country_gains} /></div></> : <Notice tone="warning">Pick a later To year.</Notice>}</Card></Section>}
    {tab === "Period comparison" && <Card className="white chart-card" title="Year-over-year comparison"><MultiSelect label="Years to compare" options={data.years} value={data.compare_years} onChange={(value) => patch("compare_years", value)} /><BarView data={data.comparison} x="year" y="trade_trillions" currency scale={1e12} loading={state.loading} onReset={resetPage} /><DataTable rows={data.comparison} columns={["year","trade_trillions","yoy_pct"]} /></Card>}
    {tab === "Underperformers" && <Section title="Underperforming regions" hint="Countries below median year-over-year growth in the focus year."><Card className="white"><div className="controls"><Select label="Focus year" value={data.focus_year} onChange={(value) => patch("focus_year", Number(value))}>{data.years.map((year) => <option key={year}>{year}</option>)}</Select></div><DataTable rows={data.underperformers} /></Card></Section>}
    <ScopeFooter scope={data.scope} /></div></>}</LoadingPage>;
}

function TableBlock({ title, rows, kind }) {
  const table = kind === "category"
    ? { columns: ["category", "change_billions", "change_pct"], columnLabels: { category: "Category", change_billions: "Changes_Billions (USD)", change_pct: "Change %" } }
    : kind === "country"
      ? { columns: ["country", "change_billions", "change_pct"], columnLabels: { country: "Country", change_billions: "Changes_Billions (USD)", change_pct: "YoY pct change" } }
      : {};
  return <div><h3 className="mb-3 text-sm font-semibold">{title}</h3><DataTable rows={rows} {...table} /></div>;
}

export function PreviewPage({ filters }) {
  const [params, setParams] = useState({ preview_rows: 1000, page: 1, page_size: 50 });
  const state = useApi("/api/trades", filters, params);
  const data = state.data;
  const patch = (key, value) => setParams((previous) => ({ ...previous, [key]: value, ...(key === "columns" ? { columns_empty: value.length === 0 } : {}), ...(key !== "page" ? { page: 1 } : {}) }));
  return <LoadingPage state={state} page="preview" title="Data preview" subtitle="Displays a reproducible random subsample of rows matching the active filters, supports column selection and pagination, and clearly separates the preview download from the full dataset.">{data && <><PageIntro title="Data preview" subtitle="Displays a reproducible random subsample of rows matching the active filters, supports column selection and pagination, and clearly separates the preview download from the full dataset." scope={data.scope} /><div className="page-stack"><Card className="white"><div className="controls"><Select label="Preview rows" value={data.preview_rows} onChange={(value) => patch("preview_rows", Number(value))}>{[100,500,1000,2000,5000].map((count) => <option key={count}>{count}</option>)}</Select><MultiSelect label="Columns" options={data.available_columns} value={data.columns} onChange={(value) => patch("columns", value)} />{data.columns.length > 0 && <a className="button inline-flex items-center gap-2" href={exportUrl(filters, { preview_rows: data.preview_rows, columns: data.columns })}><Download size={15} />Download preview CSV</a>}</div>{data.columns.length ? <DataTable rows={data.rows} columns={data.columns} /> : <Notice tone="warning">Select at least one column.</Notice>}<div className="mt-4 flex items-center justify-between"><button className="button secondary" disabled={data.page <= 1} onClick={() => patch("page", data.page - 1)}>Previous</button><span className="text-xs text-[var(--muted)]">Page {data.page} of {Math.max(1, Math.ceil(data.total_preview_rows / data.page_size))}</span><button className="button secondary" disabled={data.page * data.page_size >= data.total_preview_rows} onClick={() => patch("page", data.page + 1)}>Next</button></div><p className="section-hint mt-4">Preview contains {compact(data.total_preview_rows)} rows randomly sampled from the matching source data. It is not a complete export.</p></Card><ScopeFooter scope={data.scope} /></div></>}</LoadingPage>;
}

export function ModelsPage({ filters, onSelectCountry }) {
  const [tab, setTab] = useState("Anomalies");
  const [params, setParams] = useState({ z_threshold: 1.5, train_end: 2007, penalty: 10, shock_a_from: 2008, shock_a_to: 2009, shock_b_from: 2014, shock_b_to: 2015 });
  const anomaly = useApi("/api/models/anomalies", filters, { z_threshold: params.z_threshold });
  const oil = useApi("/api/models/oil", filters);
  const [run, setRun] = useState({ loading: {}, error: null, forecast: null, rf: null, clusters: null, correlation: null });
  const runInputKey = JSON.stringify([filters, params]);
  useEffect(() => setRun({ loading: {}, error: null, forecast: null, rf: null, clusters: null, correlation: null }), [runInputKey]);
  const execute = async (name, key = name) => {
    setRun((current) => ({ ...current, loading: { ...current.loading, [key]: true }, error: null }));
    try { const result = await api(`/api/models/${name}`, filters, params); setRun((current) => ({ ...current, loading: { ...current.loading, [key]: false }, [key]: result })); }
    catch (error) { setRun((current) => ({ ...current, loading: { ...current.loading, [key]: false }, error: error.message })); }
  };
  const patch = (key, value) => setParams((previous) => ({ ...previous, [key]: value }));
  const scope = anomaly.data?.scope || oil.data?.scope;
  if (!scope && (anomaly.loading || oil.loading)) return <><PageIntro title="Advanced models" subtitle="Runs anomaly detection, clustering, structural-break, oil-association, and forecasting diagnostics against the filtered trade history, with model limitations shown alongside the results." /><PageSkeleton page="models" /></>;
  return <><PageIntro title="Advanced models" subtitle="Runs anomaly detection, clustering, structural-break, oil-association, and forecasting diagnostics against the filtered trade history, with model limitations shown alongside the results." scope={scope} /><div className="page-stack"><Tabs items={["Anomalies","Forecast","Clusters","Correlations","Oil model"]} active={tab} onChange={setTab} />{run.error && <Notice tone="error">{run.error}</Notice>}
    {tab === "Anomalies" && <Card className="white"><div className="controls"><label className="control"><span>YoY z threshold: {params.z_threshold}</span><input type="range" min="1" max="3" step=".1" value={params.z_threshold} onChange={(event) => patch("z_threshold", Number(event.target.value))} /></label></div>{anomaly.error ? <Notice tone="error">{anomaly.error}</Notice> : anomaly.data && <div className="grid-2"><TableBlock title="Z-score anomalies" rows={anomaly.data.z_score} /><TableBlock title="Isolation Forest anomalies" rows={anomaly.data.isolation_forest} /></div>}</Card>}
    {tab === "Forecast" && <Card className="white" title="Forecast diagnostics"><div className="controls"><NumberInput label="Train through" value={params.train_end} onChange={(value) => patch("train_end", value)} /><label className="control"><span>Change-point penalty: {params.penalty}</span><input type="range" min="1" max="30" value={params.penalty} onChange={(event) => patch("penalty", Number(event.target.value))} /></label><button className="button" disabled={run.loading.forecast} onClick={() => execute("forecast")}><Play size={14} className="inline mr-2" />{run.loading.forecast ? "Running ARIMA…" : "Run ARIMA"}</button><button className="button secondary" disabled={run.loading.rf} onClick={() => execute("random-forest", "rf")}><Play size={14} className="inline mr-2" />{run.loading.rf ? "Running RF…" : "Run RF surprise"}</button></div>{run.forecast && <ModelDiagnostics data={run.forecast}><h3 className="chart-title">ARIMA forecast</h3><MultiLine data={[...run.forecast.rows.map((row) => ({ year: row.year, series: "Actual", value: row.trade_trillions })), ...run.forecast.rows.map((row) => ({ year: row.year, series: "Forecast", value: row.forecast_trillions }))]} keys={["Actual","Forecast"]} currency scale={1e12} loading={run.loading.forecast} /><Notice>Break years: {run.forecast.break_years.join(", ") || "None detected"}</Notice><DataTable rows={run.forecast.rows} /></ModelDiagnostics>}{run.rf && <ModelDiagnostics data={run.rf}><h3 className="chart-title">Random Forest surprise</h3><DataTable rows={run.rf.rows} /></ModelDiagnostics>}</Card>}
    {tab === "Clusters" && <Card className="white"><div className="controls"><NumberInput label="Shock A from" value={params.shock_a_from} onChange={(value) => patch("shock_a_from", value)} /><NumberInput label="Shock A to" value={params.shock_a_to} onChange={(value) => patch("shock_a_to", value)} /><NumberInput label="Shock B from" value={params.shock_b_from} onChange={(value) => patch("shock_b_from", value)} /><NumberInput label="Shock B to" value={params.shock_b_to} onChange={(value) => patch("shock_b_to", value)} /><button className="button" onClick={() => execute("clusters")}><Play size={14} className="inline mr-2" />Cluster countries</button></div>{run.clusters && (run.clusters.k ? <><Notice>k={run.clusters.k}, silhouette={run.clusters.silhouette?.toFixed(2)}</Notice><ScatterView data={run.clusters.rows} x="shock_a_pct" y="shock_b_pct" loading={run.loading.clusters} onSelectCountry={onSelectCountry} /><DataDisclosure rows={run.clusters.rows} /><DataTable rows={run.clusters.summary} /></> : <Notice tone="warning">At least three countries with distinct, valid shock values are required.</Notice>)}</Card>}
    {tab === "Correlations" && <Card className="white"><button className="button" disabled={run.loading.correlation} onClick={() => execute("correlation")}><Play size={14} className="inline mr-2" />{run.loading.correlation ? "Computing…" : "Compute sampled correlation"}</button>{run.correlation && <div className="mt-6"><Heatmap columns={run.correlation.columns} matrix={run.correlation.matrix} loading={run.loading.correlation} /><DataDisclosure rows={run.correlation.matrix.map((row, index) => ({ metric: run.correlation.columns[index], ...Object.fromEntries(run.correlation.columns.map((column, columnIndex) => [column, row[columnIndex]])) }))} /></div>}</Card>}
    {tab === "Oil model" && <Card className="white">{oil.error ? <Notice tone="error">{oil.error}</Notice> : oil.data && <><Notice>Association between oil trade and non-oil trade. This is not a causal estimate.</Notice>{oil.data.r2 !== null ? <div className="grid-2 mt-5"><StatCard label="In-sample R²" value={`${(oil.data.r2 * 100).toFixed(1)}%`} loading={oil.loading} /><StatCard label="Associated slope" value={oil.data.slope.toFixed(2)} loading={oil.loading} /></div> : <Notice tone="warning">{oil.data.diagnostics.warning}</Notice>}<DataTable rows={oil.data.rows} /></>}</Card>}
    <ScopeFooter scope={scope} /></div></>;
}

function ModelDiagnostics({ data, children }) { const d = data.diagnostics || {}; return <div className="mt-5 grid gap-4">{d.warning && <Notice tone="warning">{d.warning}</Notice>}{d.validation_observations && <Notice tone={d.beats_naive ? "success" : "warning"}>Train n={d.training_observations}; validation n={d.validation_observations}; MAE={d.mae?.toFixed(2)}; naive MAE={d.naive_mae?.toFixed(2)}. The model {d.beats_naive ? "beats" : "does not beat"} the naive baseline.</Notice>}{children}</div>; }

export function StoryPage({ filters, onResetFilters }) {
  const state = useApi("/api/story", filters);
  const data = state.data;
  const counterfactualRows = data ? [...data.counterfactual.map((row) => ({ year: row.year, series: "Actual", value: row.trade_trillions })), ...data.counterfactual.map((row) => ({ year: row.year, series: "Forecast", value: row.forecast_trillions }))] : [];
  return <LoadingPage state={state} page="story" title="Case study" subtitle="Connects major macro events to observed trade movements, compares actual trade with the modelled counterfactual trend, and highlights category shocks during crisis and slowdown periods.">{data && <><PageIntro title="Case study" subtitle="Connects major macro events to observed trade movements, compares actual trade with the modelled counterfactual trend, and highlights category shocks during crisis and slowdown periods." scope={data.scope} /><div className="page-stack">{!data.yearly.length ? <NoData onReset={onResetFilters} /> : <><div className="grid-4">{data.kpis.map((kpi) => <StatCard key={kpi.label} {...kpi} loading={state.loading} />)}</div><Section title="Macro events"><Card className="white"><DataTable rows={data.events} /></Card></Section>{data.counterfactual.length > 0 && <Card className="white chart-card" title="Actual vs counterfactual trend" hint={`Model trained through ${data.train_end}`}><MultiLine data={counterfactualRows} keys={["Actual","Forecast"]} currency scale={1e12} loading={state.loading} onReset={onResetFilters} /><DataDisclosure rows={counterfactualRows} /></Card>}<div className="grid-2"><TableBlock kind="category" title="2009 crisis: largest category declines" rows={data.crisis_categories} /><TableBlock kind="category" title="2015 slowdown: largest category declines" rows={data.slowdown_categories} /></div>{data.oil_timeline.length > 0 && <Card className="white chart-card" title="Oil vs total trade"><MultiArea data={data.oil_timeline} keys={["trade_trillions","oil_trillions"]} currency scale={1e12} loading={state.loading} onReset={onResetFilters} /><DataDisclosure rows={data.oil_timeline} /></Card>}</>}<ScopeFooter scope={data.scope} /></div></>}</LoadingPage>;
}
